# ref: https://docs.travis-ci.com/user/deployment/pages/

services:
  - docker

script: make

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: develop
  target-branch: master
