#+SETUPFILE: org-theme/setup/long.setup

#+AUTHOR: Manoel Vilela, Lucas Vieira
#+DATE: <2018-02-10 Sat>
#+TITLE: Common Lisp Brasil
#+LANGUAGE: bt-br
#+OPTIONS: toc:nil

#+BEGIN_ABSTRACT
Olá! Seja-bem vindo ao grupo de estudos
e projetos do Common Lisp Brasil!

Grupo *oficial* do Telegram: [[https://telegram.me/commonlispbr][Common Lisp Brasil]]

Canal do IRC não-oficial de Lisp Brasileiro no Freenode: [[http://webchat.freenode.net/][#lisp-br]]

Os dados a seguir podem estar incompletos ou conter erros. Proceda com
cuidado e, se você tiver uma sugestão ou reclamação, [[https://github.com/commonlispbr/commonlispbr.github.io][abra uma issue no
repositório desta página]].
#+END_ABSTRACT
#+TOC: headlines=2


* Sitemap

- [[file:appendix.html][Apêndice]]
- [[http://lisp.com.br/archive/][Arquivos]]
- [[http://lisp.com.br/cl-cookbook][The Common Lisp Cookbook (PT-BR) (em progresso)]]
- [[file:projects.html][Projetos]]
- [[file:rules.html][Regras]]

* Conceitos e Fundamentos
** O que é Lisp?

Lisp (historicamente, LISP) é uma família de linguagens de programação de
computadores com uma longa história e tradição. Originalmente concebida por John
McCarthy em 1958, Lisp é a segunda linguagem de programação de alto nível em uso
atualmente, advinda antes mesmo da própria Internet (somente Fortran é mais
antiga). Desde sua origem, Lisp se tornou rapidamente a linguagem favorita para
Inteligência Artificial.

Influenciada pela notação lambda Calculus de Alonzo Church, atualmente os
dialetos de Lisp de uso geral mais utilizados e conhecidos são Common Lisp,
Scheme e Clojure.

Dialetos Lisp [fn:1]  têm uma sintaxe singular simplificada para denotar, listas e
símbolos, que podem ou não estarem associados a valores e/ou
a procedimentos. Na linguagens da família Lisp, há a peculiaridade de
existir uma linha muito tênue de separação entre dados e procedimentos
no código-fonte. Na realidade, é possível produzir código a partir de
dados e vice-versa! Uma das características fortes da linguagem é o
uso da [[https://pt.wikipedia.org/wiki/Nota%25C3%25A7%25C3%25A3o_polonesa][notação polonesa]], que simplifica a sintaxe da linguagem, de forma
a previnir ambiguidades: operações e operandos são
denotados de forma explícita, em sua ordem de precedência, no uso de
listas.

#+BEGIN_SRC lisp

(operação operando-1 operando-2)
(+ 1 2) ;; => 3

#+END_SRC

Esta família de linguagens foi desenhada para abstrair a complexidade
do hardware de um computador, criando uma interface para que um humano
possa se comunicar de maneira expressiva com a máquina. O primeiro
Lisp denotado historicamente por [[https://pt.wikipedia.org/wiki/Lisp][LISP]] foi criado por [[https://pt.wikipedia.org/wiki/John_McCarthy][John McCarthy]], em
1958, nos laboratórios do MIT, USA.

[fn:1] Lisp é uma abreviação de **LISt Processing**, processamento de listas.

** O que é Common Lisp?

Common Lisp é um dialeto multi-paradigma da linguagem de programação
Lisp. Suporta os paradigmas de programação procedural, orientado a
objetos e, inclusive, o funcional, comum a todos os
Lisps, por sua próxima relação com a natureza do Cálculo Lambda.

Foi criada por Guy L. Steele nos anos 80, com o intuito de combinar
aspectos de diversos dialetos anteriores, incluindo Scheme. Em 1994
foi publicada no padrão [[http://cvberry.com/tech_writings/notes/common_lisp_standard_draft.html][ANSI Information Technology - Programming
Language - Common Lisp, registro X3.226-1994 (R1999)]]. Common Lisp é
bem maior e semanticamente mais complexa que um dialeto como Scheme,
uma vez que foi projetada para ser uma linguagem comercial e para ser
compatível com os diversos outros dialetos Lisp dos quais derivou.

#+BEGIN_SRC lisp

  (defun hello-world () ;; definição de função
    (princ "Hello, Lispers!"))

  (hello-world) ;; chamada de função

  ;; resultado: Hello, Lispers!
#+END_SRC

* Links de Aprendizado sobre Common Lisp
** Apresentação

- [[http://lisp-lang.org/][Site oficial de Common Lisp]], apresentação sobre a linguagem e seu poder.
- [[https://github.com/CodyReichert/awesome-cl][Awesome-CL]], uma lista imensa sobre frameworks e ferramentas para
  Common Lisp.
- [[http://www.lisperati.com/casting.html][Lisperati Casting]], uma história em quadrinhos sobre a magia que é
  programar em Lisp.
- [[http://www.avelino.xxx/hist%C3%B3ria-do-lisp-abra-os-olhos-para-programa%C3%A7%C3%A3o-funcional/][História do Lisp]], entenda como o Lisp começou e porque temos tantos dialetos.

** Documentação e tutoriais

- [[http://bnmcgn.github.io/lisp-guide/lisp-exploration.html][Common Lisp REPL Exploration Guide]], um guia interessantíssimo sobre
  a exploração de Common Lisp pelo REPL [fn:2].
- [[https://lispcookbook.github.io/cl-cookbook/][Cookbook de Common Lisp]], atualmente com uma [[lisp.com.br/cl-cookbook][tradução para o Português em andamento]], feita pela comunidade.
  Também inclui tutoriais sobre Quicklisp (veja a seção de Tooling).
- [[http://www.lispworks.com/documentation/HyperSpec/Front/][Common Lisp Hyperspec]]
  Sua primeira parada ao pesquisar por documentação de Common Lisp. [[http://clhs.lisp.se/][(Mirror)]]
- [[https://www.cliki.net/][CLiki, a Wiki de Common Lisp]]

[fn:2] REPL significa Read-Eval-Print-Loop, muito comum em linguagens
interativas como Lisp e Python. A propósito, o conceito foi
inicialmente feito justamente em Lisp!

** Livros

- Common Lisp: A Gentle Introduction to Symbolic Computation, por David S. Touretsky
  - [Amazon] [[https://www.amazon.com.br/Common-LISP-Introduction-Computation-Engineering-ebook/dp/B00IZUEG1G/][Livro físico]]
  - [[https://www.cs.cmu.edu/~dst/LispBook/][Versão online]]
- [Amazon] [[https://www.amazon.com.br/Land-Lisp-Learn-Program-Game-ebook/dp/B004AE3P4K/][Land of Lisp: Learn to Program in Lisp, One Game at a Time!]], por Conrad Barski
- [Amazon] [[https://www.amazon.com.br/Common-Lisp-Recipes-Problem-Solution-Approach-ebook/dp/B01JFTONBS/][Common Lisp Recipes: A Problem-Solution Approach]], por Edmund Weitz
- Practical Common Lisp, por Peter Seibel
  - [Amazon] [[https://www.amazon.com.br/Practical-Common-Lisp-Peter-Seibel/dp/1590592395][Livro físico]]
  - [[http://www.gigamonkeys.com/book/][Versão online]]

* Tooling

** Emacs

Emacs é, consensualmente, o melhor editor de texto para se programar em
Common Lisp.

- [Inglês] [[https://www.gnu.org/software/emacs/][Site oficial]]
- [Inglês] [[https://github.com/bbatsov/prelude][Prelude]] uma configuração com baterias pro Emacs para bons hábitos
- [Inglês] Mini-manual do Emacs, por [[https://github.com/tuhdo][tuhdo]]
  - [[http://tuhdo.github.io/emacs-tutor.html][Parte 1: O Básico]]
  - [[http://tuhdo.github.io/emacs-tutor2.html][Parte 2: Por que parênteses importam]]
  - [[http://tuhdo.github.io/emacs-tutor3.html][Parte 3: Customizando e extendendo o Emacs]]

** Portacle

Portacle é um reempacotamento de Emacs. Diferente do programa original,
Portacle é uma edição voltada para programadores Common Lisp. Este editor
já inclui o SBCL (implementação de Common Lisp), Quicklisp (para gerenciar
projetos e pacotes), e Magit (para lidar com versionamento de código em
Git). Enquanto recomendamos instalar o Emacs e aprender a configurá-lo,
esta é também uma excelente ferramenta para iniciantes que queiram um
ambiente Common Lisp que funcione logo de cara, ou mesmo para lispeiros
experientes que queiram um ambiente CL que possam carregar no pendrive,
e que funcione em quase qualquer sistema operacional.

- [Inglês] [[https://portacle.github.io/][Link oficial do Portacle]]
- [Inglês] [[https://github.com/portacle/portacle][Repositório oficial]]

** SLIME

SLIME significa /SUPERIOR LISP INTERACTION MODE for EMACS/. É uma
das coisas mais fascinante que se faz Common Lisp uma linguagem tão
produtiva e o Emacs ser seu editor ideal.

- [Inglês] [[https://astraybi.wordpress.com/2015/08/02/how-to-install-slimesbclquicklisp-into-emacs/][Instalando SLIME + SBCL + Quicklisp no Emacs]], por Astray_BI
- [Inglês] [[https://github.com/quicklisp/quicklisp-slime-helper][Repositório do =quicklisp-slime-helper=]]

  Este pacote torna mais fácil a instalação do SLIME, a partir do
  Quicklisp.

** Compiladores

- [Inglês] [[http://sbcl.org/][SBCL]]: Steel Bank Common Lisp (recomendado)
- [Inglês] [[https://common-lisp.net/project/ecl/][ECL]]: Embedabble Common Lisp
- [Inglês] [[https://clisp.sourceforge.io/][GNU CLISP]] (obsoleto desde 2010, artefato histórico)
- [Inglês] [[https://ccl.clozure.com/][CCL]]: Clozure Common Lisp ([[https://clojure.org/][Clojure]] é outra coisa, não confunda!)

** Quicklisp

Quicklisp é o gerenciador de pacotes (systems, nos jargões de CL),
muito útil para integrar sua aplicação usando pacotes de terceiros.

- [Inglês] [[https://www.quicklisp.org/beta/][Site oficial do Quicklisp]]
- [Inglês] [[https://www.xach.com/lisp/quickproject/][Quickproject: crie o esqueleto de um projeto de Common Lisp]]

  Este tutorial é extremamente útil para a criação de projetos
  compatíveis com Quicklisp.

** Roswell

Roswell é descrito como sendo o instalador de implementações de
Common Lisp, bem como um launcher para o ambiente em geral de
Common Lisp, que simplesmente funciona.
Tenta automatizar a instalação dos compiladores, pacotes do Emacs
e criação de binários com Common Lisp. Vale a pena tentar dar uma
olhada!

- [Inglês] [[https://github.com/roswell/roswell][Repositório oficial]]
