* O que é Lisp?

Lisp é uma família de linguagens de programação de computadores com
uma longa história e tradição. O primeiro Lisp denotado historicamente
por [[https://pt.wikipedia.org/wiki/Lisp][LISP]] foi criado por [[https://pt.wikipedia.org/wiki/John_McCarthy][John McCarthy]], em 1958, nos laboratórios de
inteligência artificial do MIT, USA., Lisp é a segunda linguagem de
programação de alto nível mais antiga ainda em uso atualmente, advinda
antes mesmo da própria Internet (somente Fortran é mais antiga). Desde
sua origem, Lisp se tornou rapidamente a linguagem favorita para
Inteligência Artificial.

Dialetos Lisp [fn:1] têm uma sintaxe singular simplificada para
denotar, listas e símbolos, que podem ou não estarem associados a
valores e/ou a procedimentos. Na linguagens da família Lisp, há a
peculiaridade de existir uma linha muito tênue de separação entre
dados e procedimentos no código-fonte. Na realidade, é possível
produzir código a partir de dados e vice-versa! Uma das
características fortes da linguagem é o uso da [[https://pt.wikipedia.org/wiki/Nota%25C3%25A7%25C3%25A3o_polonesa][notação polonesa]], que
simplifica a sintaxe da linguagem, de forma a previnir ambiguidades:
operações e operandos são denotados de forma explícita, em sua ordem
de precedência, no uso de listas.

#+BEGIN_SRC lisp

(operação operando-1 operando-2)
(+ 1 2) ;; => 3

#+END_SRC

Esta família de linguagens foi desenhada para abstrair a complexidade
do hardware de um computador, criando uma interface para que um humano
possa se comunicar de maneira expressiva com a máquina. Influenciada
pela linguagem de computação teórica Lambda Calculus de Alonzo Church,
atualmente os dialetos de Lisp de uso geral mais utilizados e
conhecidos são Common Lisp, Scheme e Clojure.

[fn:1] Lisp é uma abreviação de **LISt Processing**, processamento de listas.

* O que é Common Lisp?

Common Lisp é um dialeto multi-paradigma da linguagem de programação
Lisp. Suporta os paradigmas de programação procedural, orientado a
objetos e, inclusive, o funcional, comum a todos os
Lisps, por sua próxima relação com a natureza do Cálculo Lambda.

Foi criada por Guy L. Steele nos anos 80, com o intuito de combinar
aspectos de diversos dialetos anteriores, incluindo Scheme. Em 1994
foi publicada no padrão [[http://cvberry.com/tech_writings/notes/common_lisp_standard_draft.html][ANSI Information Technology - Programming
Language - Common Lisp, registro X3.226-1994 (R1999)]]. Common Lisp é
bem maior e semanticamente mais complexa que um dialeto como Scheme,
uma vez que foi projetada para ser uma linguagem comercial e para ser
compatível com os diversos outros dialetos Lisp dos quais derivou.

#+BEGIN_SRC lisp

  (defun hello-world () ;; definição de função
    (princ "Hello, Lispers!"))

  (hello-world) ;; chamada de função

  ;; resultado: Hello, Lispers!
#+END_SRC
